POST http://localhost:3333/networkweb/create/1946/1/0bD7e56e2216450828E127ad2235B77e52C0fcb2 
###
POST http://localhost:3333/networkweb/add/1989/3


###
POST http://localhost:3333/network/add/20/2

###
POST http://localhost:3333/network/add/8/4

###
DELETE http://localhost:3333/node/2/1 HTTP/1.1

###
delete http://localhost:3333/network/1

###
get http://localhost:3333/network/procesos/20

### 
get http://localhost:3333/network/reload/20

### Listado redes(es el get("/" del router-network
get http://localhost:3333/network

### Listado nodos
get http://localhost:3333/network