POST http://localhost:3333/networkweb/create/5/1/0bD7e56e2216450828E127ad2235B77e52C0fcb2/9666/10000 
###
POST http://localhost:3333/networkweb/add/3/4

###
POST http://localhost:3333/node/add/1/3
###
POST http://localhost:3333/node/delete/1/2
###
POST http://localhost:3333/network/add/1/2

###
POST http://localhost:3333/network/add/8/4

###
DELETE http://localhost:3333/node/2/2 HTTP/1.1

###
delete http://localhost:3333/networkweb/delete/1946

###
get http://localhost:3333/network/procesos/20

### 
get http://localhost:3333/network/reload/8

### Listado redes(es el get("/" del router-network
get http://localhost:3333/network

### Listado nodos
get http://localhost:3333/network/1

### Consulta balance
get http://localhost:3333/faucet/balance/0xBEb2f649a3A14866D06D41Baaba7Db25b7638B0E
